# Generated by Django 3.2.5 on 2021-08-25 04:03

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0005_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRank',
            fields=[
            ],
            options={
                'verbose_name': '8월 갤창랭킹',
                'verbose_name_plural': '8월 갤창랭킹',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.post',),
        ),
    ]
