# Generated by Django 3.2.5 on 2021-12-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_rank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postrank',
            options={'verbose_name': '12월 갤창랭킹', 'verbose_name_plural': '12월 갤창랭킹'},
        ),
    ]
