version: '3.9'
services:
  django:
    image: django
    command: sh -c "gunicorn --bind 0:8000 server.wsgi:application"
    environment:
      TZ: "Asia/Seoul"
    network_mode: "host"
    restart: always
  celery:
    image: django
    command: sh -c "celery -A server worker -l INFO"
    environment:
      TZ: "Asia/Seoul"
    network_mode: "host"
    restart: always
  celery-beat:
    image: django
    command: sh -c "celery -A server beat -l INFO"
    environment:
      TZ: "Asia/Seoul"
    network_mode: "host"
    restart: always
  celery-flower:
    image: django
    command: sh -c "celery -A server flower --port=5555"
    environment:
      TZ: "Asia/Seoul"
    network_mode: "host"
    restart: always
  nginx:
    image: nginx:latest
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/certificate.crt:/etc/ssl/certificate.crt"
      - "./nginx/private.key:/etc/ssl/private.key"
      - "./static:/etc/nginx/django/static"
    command: nginx -g 'daemon off;'
    depends_on:
      - django
      - celery
      - celery-beat
      - celery-flower
    network_mode: "host"
    restart: always
