version: '3.9'
services:
  django:
    image: django
    command: sh -c "gunicorn --bind 0:8000 -k gevent server.wsgi:application --access-logfile - --access-logformat '%(t)s [%(h)s] %(U)s?%(q)s' 2>&1 | tee -a gunicorn.log" # --log-level debug
    volumes:
      - "./logfile.log:/usr/src/app/logfile.log"
      - "./gunicorn.log:/usr/src/app/gunicorn.log"
    environment:
      TZ: "Asia/Seoul"
    network_mode: "host"
    restart: always
  celery:
    image: django
    command: sh -c "celery -A server worker -l WARN"
    environment:
      TZ: "Asia/Seoul"
      DJANGO_LOG_LEVEL: "INFO"
    network_mode: "host"
    restart: always
  celery-beat:
    image: django
    command: sh -c "celery -A server beat -l WARN"
    environment:
      TZ: "Asia/Seoul"
    network_mode: "host"
    restart: always
  celery-flower:
    image: django
    command: sh -c "celery -A server flower --port=5555"
    environment:
      TZ: "Asia/Seoul"
    network_mode: "host"
    restart: always
  # sinatra:
  #   image: sinatra
  #   command: sh -c "bundle exec rackup --host 0.0.0.0 -p 4567"
  #   environment:
  #     TZ: "Asia/Seoul"
  #   network_mode: "host"
  #   restart: always
  nginx:
    image: nginx:latest
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/certificate.crt:/etc/ssl/certificate.crt"
      - "./nginx/private.key:/etc/ssl/private.key"
      - "./static:/etc/nginx/django/static"
    command: nginx -g 'daemon off;'
    environment:
      TZ: "Asia/Seoul"
    depends_on:
      - django
      - celery
      - celery-beat
      - celery-flower
    network_mode: "host"
    restart: always
