version: '3.9'
services:
  django:
    image: django
    command: sh -c "gunicorn --bind 0:8000 server.wsgi:application"
    network_mode: "host"
    restart: always

  celery:
    image: django
    command: sh -c "celery -A server worker -l INFO"
    network_mode: "host"
    restart: always

  celery-beat:
    image: django
    command: sh -c "celery -A server beat -l INFO"
    network_mode: "host"
    restart: always

  celery-flower:
    image: django
    command: sh -c "celery -A server flower --port=5555"
    network_mode: "host"
    restart: always
