# Generated by Django 3.2.5 on 2021-07-03 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0003_auto_20210701_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPost',
            fields=[
                ('num', models.OneToOneField(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='detail', serialize=False, to='post.post')),
                ('detail', models.TextField()),
            ],
            options={
                'db_table': 'detail_post',
            },
        ),
    ]
