# Generated by Django 3.2.5 on 2021-08-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailpost',
            options={'verbose_name': '캐시된 게시글', 'verbose_name_plural': '캐시 목록'},
        ),
    ]
