# Generated by Django 3.2.4 on 2021-06-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=60)),
                ('idip', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=19)),
                ('comment_count', models.IntegerField()),
                ('gall_count', models.IntegerField()),
                ('gall_recommend', models.IntegerField()),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
