# Generated by Django 3.2.4 on 2021-07-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='gall_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='gall_recommend',
            field=models.IntegerField(null=True),
        ),
    ]
