# Generated by Django 3.2.5 on 2021-08-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '게시글', 'verbose_name_plural': '글 목록'},
        ),
    ]
