# Generated by Django 3.2.5 on 2021-12-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='newdate',
            field=models.DateTimeField(null=True),
        ),
    ]
