# Generated by Django 3.2.5 on 2021-12-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_newdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
