# Generated by Django 3.2.5 on 2021-12-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='newdate',
            new_name='date',
        ),
    ]
