# Generated by Django 3.2.5 on 2021-07-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BPost',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=320)),
                ('name', models.CharField(max_length=120)),
                ('idip', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=19)),
                ('comment_count', models.IntegerField(null=True)),
                ('gall_count', models.IntegerField(null=True)),
                ('gall_recommend', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'bpost',
            },
        ),
    ]
