# Generated by Django 3.2.5 on 2021-08-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_back', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bpost',
            options={'verbose_name': '게시글 (백업)', 'verbose_name_plural': '글 목록 (백업)'},
        ),
    ]
