# Generated by Django 3.2.5 on 2021-08-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_back', '0002_alter_bpost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bpost',
            options={'verbose_name': '게시글 (백업) - 클릭자제 (매우 느림)', 'verbose_name_plural': '글 목록 (백업) - 클릭자제 (매우 느림)'},
        ),
    ]
